name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check_and_clippy_nightly:
    name: Clippy check on nightly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: clippy

      - name: Run Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy

  check_and_clippy_stable:
    name: Clippy check on stable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
            components: clippy

      - name: Run Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
